name-template: v$NEXT_MINOR_VERSION
tag-template: v$NEXT_MINOR_VERSION
version-template: v$MAJOR.$MINOR.$PATCH
category-template: '### $TITLE'
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - enhancement
      - feature
  patch:
    labels:
      - fix
      - CI/CD
      - documentation
  default: patch

categories:
  - title: 大更新
    labels:
      - major
  - title: 🎨 新特性
    labels:
      - feature
  - title: 🚀 优化/提升
    labels:
      - enhancement
  - title: 🐛 Bug修复
    labels:
      - fix
  - title: CI/CD
    labels:
      - CI/CD
  - title: 📝 文档更新
    labels:
      - documentation
  - title: ✍ Other changes
sort-by: title
sort-direction: ascending
template: |
  ## 更新事项

  $CHANGES
autolabeler:
  - label: documentation
    files:
      - '*.md'
    branch:
      - '/^docs-.+/'
      - '/^chore-.+/'
  - label: fix
    branch:
      - '/^fix-.+/'
  - label: feature
    branch:
      - '/^feat-.+/'
      - '/^style-.+/'
  - label: CI/CD
    branch:
      - '/^ci-.+/'
      - '/^build-.+/'
  - label: enhancement
    branch: 
      - '/^refactor-.+/'
      - '/^enh-.+/'